[versions]

compileSdk = "31"
minSdk = "23"

kotlin-lang = "1.6.10"
android-gradle-plugin = "7.1.2"
kotlinter = "3.9.0"
maven-publish = "0.19.0"

kotlin-serialization = "1.3.2"
android-sdkCommon = "30.0.3"
androidx-activityCompose = "1.4.0"
androidx-core = "1.8.0-alpha05"
androidx-constraint-layout = "1.0.0"
accompanist-main = "0.23.1"
coil = "1.4.0"
compose-main = "1.1.1"
compose-navigation = "2.4.1"
square-kotlinPoet = "1.10.2"

[libraries]

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin-lang" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-lang" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
android-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-sdkCommon" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraint-layout" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist-main" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-main" }
accompanist-systemController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-main" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose-main" }
compose-animationGraphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose-main" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-main" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose-main" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-main" }
compose-materialRipple = { module = "androidx.compose.material:material-ripple", version.ref = "compose-main" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-main" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-main" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose-main" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-main" }
compose-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-main" }
compose-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose-main" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-main" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-main" }
compose-uiUtil = { module = "androidx.compose.ui:ui-util", version.ref = "compose-main" }
compose-viewBinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose-main" }
square-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "square-kotlinPoet" }

[bundles]
